add_library(
    stm32f10x
    STATIC

    ${CMAKE_CURRENT_LIST_DIR}/core_cm3.c
    ${CMAKE_CURRENT_LIST_DIR}/system_stm32f10x.c
    ${CMAKE_CURRENT_LIST_DIR}/src/misc.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_adc.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_bkp.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_can.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_cec.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_crc.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_dma.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_exti.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_flash.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_fsmc.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_gpio.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_i2c.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_iwdg.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_pwr.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_rcc.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_rtc.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_spi.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_tim.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_usart.c
    ${CMAKE_CURRENT_LIST_DIR}/src/stm32f10x_wwdg.c
)

include_directories(${CMAKE_CURRENT_LIST_DIR}/)
include_directories(${CMAKE_CURRENT_LIST_DIR}/inc/)
